import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'
import { createRunEvidenceViewModel, reviewStatusLabel } from '../src/features/trace/runEvidenceViewModel.ts'
import type { AgentRunTrace, AgentStep, GenerationRecord, GenerationTrace, HumanReview, ToolCallRecord } from '../src/types/domain.ts'

function step(id: number, stepOrder: number, overrides: Partial<AgentStep> = {}): AgentStep { return { id, runId: 9, stepOrder, stepType: 'PROMPT_RENDER', stepName: `步骤 ${id}`, status: 'SUCCESS', summary: `摘要 ${id}`, latencyMs: id, startedAt: '2026-07-29T10:00:00', completedAt: '2026-07-29T10:00:01', ...overrides } }
function tool(id: number, stepId?: number): ToolCallRecord { return { id, runId: 9, stepId, toolName: `tool-${id}`, status: 'SUCCESS', latencyMs: id, createdAt: '2026-07-29T10:00:00' } }
function review(status: string): HumanReview { return { id: 1, runId: 9, generationRecordId: 90, reviewStatus: status, reviewer: 'manual', comment: '真实复核意见', createdAt: '2026-07-29T10:00:00' } }
function record(overrides: Partial<GenerationRecord> = {}): GenerationRecord { return { id: 90, projectId: 1, generationType: 'requirement-split', inputSummary: '输入', inputContent: '输入内容', outputContent: '输出', status: 'READY_FOR_REVIEW', confirmed: false, costTimeMs: 20, success: true, version: 1, createdAt: '2026-07-29T10:00:00', ...overrides } }
function generationTrace(overrides: Partial<GenerationTrace> = {}): GenerationTrace { return { id: 1, generationRecordId: 90, status: 'SUCCESS', createdAt: '2026-07-29T10:00:00', ...overrides } }
function trace(steps: AgentStep[], tools: ToolCallRecord[] = [], reviews: HumanReview[] = []): AgentRunTrace { return { run: { id: 9, projectId: 1, generationRecordId: 90, title: '真实 Trace', status: 'READY_FOR_REVIEW', createdAt: '2026-07-29T10:00:00' }, steps, toolCalls: tools, humanReviews: reviews } }

test('按 stepOrder 排序，且不补造固定步骤', () => { const result = createRunEvidenceViewModel({ trace: trace([step(3, 30), step(1, 10)]) }); assert.deepEqual(result.events.map((item) => item.stepId), [1, 3]); assert.equal(result.events.length, 2) })
test('Tool Call 仅按 stepId 关联，并保留 Run-level 证据', () => { const result = createRunEvidenceViewModel({ trace: trace([step(1, 1), step(2, 2)], [tool(1, 1), tool(2, 1), tool(3), tool(4, 999)]) }); assert.equal(result.events[0].toolCalls.length, 2); assert.equal(result.events[1].toolCalls.length, 0); assert.deepEqual(result.unlinkedToolCalls.map((item) => item.id), [3, 4]) })
test('Provider / Model 记录真实来源字段且无默认值', () => { const base = trace([step(1, 1)]); const result = createRunEvidenceViewModel({ trace: { ...base, run: { ...base.run, providerName: 'local-rule', modelName: 'local-rule-mvp' } }, records: [record({ providerName: 'record-provider' })], generationTraces: [generationTrace({ providerName: 'trace-provider', modelName: 'trace-model' })] }); assert.equal(result.provider.value, 'local-rule'); assert.equal(result.provider.source, 'AgentRun.providerName'); assert.equal(result.model.value, 'local-rule-mvp'); assert.equal(result.model.source, 'AgentRun.modelName'); assert.equal(result.routeEvidence.value, '本地演示路由') })
test('errorEvidence 不等于 fallbackEvidence；只有明确 FALLBACK 状态才叫降级', () => { const errorOnly = createRunEvidenceViewModel({ trace: trace([step(1, 1)]), records: [record({ errorMessage: 'provider error' })], generationTraces: [generationTrace()] }); assert.equal(errorOnly.errorEvidence.availability, 'direct'); assert.equal(errorOnly.fallbackEvidence.availability, 'unavailable'); const fallback = createRunEvidenceViewModel({ trace: { ...trace([step(1, 1)]), run: { ...trace([step(1, 1)]).run, status: 'FALLBACK' } }, records: [record()] }); assert.equal(fallback.fallbackEvidence.availability, 'direct') })
test('无 Knowledge Step 不产生 Attention；有 Knowledge Step 无引用才产生 Evidence Gap', () => { const noKnowledge = createRunEvidenceViewModel({ trace: trace([step(1, 1)]), records: [record()], generationTraces: [generationTrace()] }); assert.equal(noKnowledge.knowledgeState, 'unused'); assert.equal(noKnowledge.derivedAttention.some((item) => item.includes('知识')), false); const missingReference = createRunEvidenceViewModel({ trace: trace([step(1, 1, { stepType: 'KNOWLEDGE_RETRIEVAL' })]), records: [record()], generationTraces: [generationTrace()] }); assert.equal(missingReference.knowledgeState, 'evidence-gap'); assert.equal(missingReference.derivedAttention.some((item) => item.includes('证据缺口')), true) })
test('Review 状态不推断完成，Pending / Confirmed / Rejected 正确区分', () => { const noReview = createRunEvidenceViewModel({ trace: trace([step(1, 1)]) }); assert.equal(noReview.review.statusLabel, '未进入人工复核'); assert.equal(reviewStatusLabel('PENDING'), '等待人工复核'); assert.equal(reviewStatusLabel('CONFIRMED'), '复核已确认'); assert.equal(reviewStatusLabel('REJECTED'), '复核已驳回'); const actual = createRunEvidenceViewModel({ trace: trace([step(1, 1)], [], [review('CONFIRMED')]) }); assert.equal(actual.review.availability, 'direct') })
test('Failed Step、缺少 Generation 与长中文 / JSON 保持稳定', () => { const longChinese = '这是一段用于验证长中文布局不会被适配层截断的说明。'.repeat(20); const result = createRunEvidenceViewModel({ trace: trace([step(1, 1, { status: 'FAILED', summary: longChinese }), step(2, 2, { summary: JSON.stringify({ payload: longChinese }) })]) }); assert.equal(result.events[0].tone, 'error'); assert.equal(result.record, undefined); assert.doesNotThrow(() => JSON.stringify(result.normalizedSnapshot)) })
test('Review Reason 使用 HUMAN_REVIEW summary，缺失时不推断', () => { const reason = '需要人工确认订单接口缓存策略是否覆盖异常路径。'; const actual = createRunEvidenceViewModel({ trace: trace([step(1, 1), step(2, 2, { stepType: 'HUMAN_REVIEW', summary: reason })], [], [review('PENDING')]) }); assert.equal(actual.review.reason.value, reason); assert.equal(actual.review.reason.source, 'AgentStep.summary'); assert.equal(actual.review.reason.availability, 'direct'); const missingReason = createRunEvidenceViewModel({ trace: trace([step(1, 1)], [], [review('PENDING')]) }); assert.equal(missingReason.review.reason.availability, 'unavailable') })
test('Trace 与 App Shell 相关业务文本不使用 8px / 9px 字体', () => { const root = resolve(import.meta.dirname, '..'); const files = ['src/styles/evidence-workspace.css', 'src/styles/theme.css', 'src/features/trace/components/EvidenceEventRow.vue', 'src/features/trace/components/EvidenceInspector.vue', 'src/components/TopBar.vue']; const offenders = files.flatMap((file) => { const content = readFileSync(resolve(root, file), 'utf8'); return [...content.matchAll(/font-size:\s*(8|9)px/g)].map((match) => `${file}:${match.index}`) }); assert.deepEqual(offenders, []) })
